### ISSUE TITLE
编写不用redux的React代码

### ISSUE THREAD

**Issue by helios741** [helios741/myblog#21]
## 背景
最近把同事的项目接了一下，准备按照自己的想法重构一遍的时候发现自己的写或者重构React代码的时候还是没有代码标杆。有的时候按照想法A写了一下，不知不觉的有改到了另一种格式。

## 业务场景

业务属于不算复杂的TO B业务的后台管理系统。如下几个图：
### 列表图
![user](https://user-images.githubusercontent.com/12036324/46129542-a0354380-c269-11e8-84ae-34f11e8455f1.png)

### 详情图

![user-detail](https://user-images.githubusercontent.com/12036324/46129624-dd013a80-c269-11e8-892a-c40f7ad6966b.png)
点击`租户绑定`中的修改的时候，弹出一个modal框进行进行修改资源，如下图：
![user - detail - re su](https://user-images.githubusercontent.com/12036324/46129747-3bc6b400-c26a-11e8-9b46-e3334056bf58.png)

所有的管理界面基本都是大同小异，先进列表页（列表页中包含新建等相关操作），然后详情页面，详情页面能对某个东西进行修改。

## 技术栈

因为在项目中虽然引用了Redux但是从来没有使用过，所以现在的技术栈为`Webpack+React+Typescript+React-router(+Redux)`为什么在这里给redux加上个括号，是因为现在有给项目加上Redux的打算。
脚手架是同事搭建的，针对公司业务的。自己有一套脚手架的好处就是有技术或者组件沉淀的时候就可以打包在脚手架里面。
组件库是基于`rc-component`封装了一套业务组件。有的业务线使用的`antd`。

## 技术架构

这里用**技术架构**可能有点高大上，但是实在想不出什么朴实的词汇。

虽然现在没有使用redux，但是还是借鉴了Redux中有状态组件和无状态组件的思想。
有状态组件负责：
- 调用接口获取数据
- 存储数据
- 处理用户响应（来更新数据）

无状态组件负责：
- 展示数据
- 向父组件传递实践响应
- 存储必要的state（比如详情页面中，租户绑定[不要关心租户是什么概念]，就是一个组件，修改按钮的modal的展示就放在这个组件中进行维护）

项目目录如下：

```
├── Makefile
├── README.md
├── mock
│   └── hello
├── package-lock.json
├── package.json
├── pre-commit
├── project.config.js
├── src
│   ├── app
│   │   ├── action.ts
│   │   ├── app.less
│   │   ├── app.tsx
│   │   ├── dao
│   │   │   ├── user.ts
│   │   │   └── workspace.ts
│   │   ├── reducer
│   │   │   └── index.ts
│   │   ├── root-reducer.ts
│   │   ├── root-router.tsx
│   │   ├── type
│   │   │   └── index.ts
│   │   └── type.ts
│   ├── common
│   │   ├── component
│   │   │   ├── form
│   │   │   │   ├── custom-validator.ts
│   │   │   │   └── index.tsx
│   │   │   └── user-form-dialog
│   │   │       ├── index.tsx
│   │   │       ├── user-form-dialog.less
│   │   │       └── user-form-dialog.less.d.ts
│   │   ├── css
│   │   │   └── global.less
│   │   ├── schemas
│   │   │   └── user.ts
│   │   ├── conf
│   │   │   └── validation
│   │   │       ├── user-list.ts
│   │   └── util
│   │       ├── field-value.ts
│   ├── index.html
│   ├── types
│   │   ├── classnames.d.ts
│   │   ├── lodash.chunk.d.ts
│   │   ├── rc-select.d.ts
│   │   └── validator.d.ts
│   ├── user
│   │   ├── create-ldap
│   │   │   ├── component
│   │   │   │   └── ldap-form-dialg
│   │   │   │       ├── index.tsx
│   │   │   │       ├── ldap-form-dialog.less
│   │   │   │       └── ldap-form-dialog.less.d.ts
│   │   │   ├── create-ldap.less
│   │   │   ├── create-ldap.less.d.ts
│   │   │   └── index.tsx
│   │   ├── create-user
│   │   │   ├── create-user.less
│   │   │   ├── create-user.less.d.ts
│   │   │   └── index.tsx
│   │   ├── user-detail
│   │   │   ├── index.tsx
│   │   │   ├── user-detail.less
│   │   │   └── user-detail.less.d.ts
│   │   ├── user-ldap
│   │   │   ├── component
│   │   │   │   └── ladp-detail
│   │   │   │       ├── index.tsx
│   │   │   │       ├── ldap-detail.less
│   │   │   │       └── ldap-detail.less.d.ts
│   │   │   ├── index.tsx
│   │   │   ├── user-ldap.less
│   │   │   └── user-ldap.less.d.ts
│   │   └── user-list
│   │       ├── index.tsx
│   │       ├── user.less
│   │       └── user.less.d.ts
├── static.d.ts
├── tsconfig.json
├── tslint.js
└── typings
    ├── globals
    │   └── index.d.ts
    └── index.d.ts
```

介绍一下几个非业务的目录：

### app

这个目录的定位是工程的入口文件。主要有*合并reducer*，*定义redux中action type*以及*配置路由*。

### common

这么目录是存放一些通用的东西，包括但是不限于:

- `component`: 通用组件
- `css`: 全局的css
- `conf`
    + `validation`: 填写表单时候的字段校验
- `utils`:常用通用方法
- `schemas`: 定义typescript的要用到的通用类型

### types

针对于typescript来讲的如果没有@type对应的组件库，就要自己实现一下。但是公司里这个文件一般是这个样子的：

```javascript
declare  module 'rc-select' {
    const Select: any;
    export default Select;
}
```
对，就是这么简单粗暴的声明。

其他的就都是业务目录的。

## 开发模式

公司的业务分为不同的产品，每个产品在不同的`repo`下开发，我负责的这个产品算我在内有两个人开发，主要的东西还是我一个人开发。

开发模式采用当下比较流行的**Feature Branching**的开发方式，即使每个feature或者bugfix分为不同的分支，等开发完成之后向主分支（现在是develop是主分支）提一个**pull request**。然后develop分支就会触发CICD的流程，部署到开发环境，来看线上的效果。

但是这种开发模式，遇到了一个问题：
``` Text
A分支是1.0版本的上线分支；
develop是目前的开发分支；
每当A分支上有bug的时候会开一个新的分支去修复bug，然后把这个分支在merge到develop分支上来保证bug也在开发分支上进行了fix，
但是--------------------------
develop分支进行很大的重构，文件目录也进行了很大的变化。
当A分支上又有一个bug的时候，就不能通过pull request的方式，简单merge回develop分支了。
就要一份代码还要在develop上在copy一次。
```

## 业务组件的架构

真的不想叫架构这么高大上的名字，也不能叫**文件目录的放置**吧。

上文也是说到了分为有状态组件和无状态组件。
按照user这个目录来说：
```
user
├── component
│   ├── user-detail
│   │   ├── index.tsx
│   │   ├── user-detail.less
│   │   └── user-detail.less.d.ts
│   ├── user-detail-ak
│   │   ├── index.tsx
│   │   ├── user-detail-ak.less
│   │   └── user-detail-ak.less.d.ts
│   ├── user-detail-base-info
│   │   └── index.tsx
│   ├── user-detail-resource
│   │   ├── index.tsx
│   │   ├── user-detail-resource.less
│   │   └── user-detail-resource.less.d.ts
│   ├── user-detail-workspace
│   │   └── index.tsx
│   └── user-form-dialog
│       ├── index.tsx
│       ├── user-form-dialog.less
│       └── user-form-dialog.less.d.ts
├── create-ldap
│   ├── component
│   │   └── ldap-form-dialg
│   │       ├── index.tsx
│   │       ├── ldap-form-dialog.less
│   │       └── ldap-form-dialog.less.d.ts
│   ├── create-ldap.less
│   ├── create-ldap.less.d.ts
│   └── index.tsx
├── create-user
│   ├── create-user.less
│   ├── create-user.less.d.ts
│   └── index.tsx
├── user-detail-wrapper
│   └── index.tsx
├── user-ldap
│   ├── index.tsx
│   ├── user-ldap.less
│   └── user-ldap.less.d.ts
├── user-ldap-detail-wrapper
│   ├── index.tsx
│   ├── user-ldap-detail-wrapper.less
│   └── user-ldap-detail-wrapper.less.d.ts
└── user-list
    ├── index.tsx
    ├── user.less
    └── user.less.d.ts
```

并没有*redux*中**containers**的目录，因为感觉到并没有使用*redux*，所以就没有使用**containers**的概念。
但是也是可以把user中的组件分为两种组件，一种是**component**的里面的组件，另一种是非**component**中的组件。_^__^_
component组件承担是无状态组件的责任，非component组件承担的是有状态组件的责任。
虽然这个模式规范一致在心中，但是实现的时候难免会一些偏差。

### 遇到的偏差

遇到的问题就是：**心中的这份规范并不是很明确**。
第一次重构代码完，一个有状态组件的`render`函数如下：

```React
render() {
    return (
      <Fragment>
        <div className={style.header}>用户管理</div>
        <AdvancedTable
          onLoad={(params: IParams) => this.handleLoad(params)}
          listOutOfDate={this.state.listOutOfDate}
          toolbar={this.toolbarProps()}
          table={this.tableProps()}
          pagination={{ total: this.state.total }}
        />
      </Fragment>
    );
  }
```

后来当我重构另一个功能的时候一个有状态组件的`render`函数是下面这样的：

```React
render() {
    const { total, list } = this.state;
    return (
      <ResourceList
        total= {total}
        onLoad={(params: IParams) => this.onLoad(params)}
        onAdd={() => this.onAdd()}
        jump={(yarn: IYarnEntity) => this.jump(yarn)}
        list={list}
        title="Hadoop管理"
        cols={this.columns}
      />
    );
  }

```

后面这份代码和上面的代码相比来说组件抽象的组件更加完全。
第一个组件虽然做到了有状态组件的功能，但是还是不够，因为`Table`组件传递的参数还是在这个有状态组件中传递的；

第一个组件中的`<div className={style.header}>用户管理</div>`还是应该在是无状态组件管辖的范围。

## 结果

现在的结果就造成了，看一个月之前的代码看着就很不舒服，又想着慢慢重构。
本来想着这么做都是为了后面引入redux的做铺垫，但是现在这个感觉铺垫的时间要加长了。

**Comment by helios741** [comment]
现在思考一下为什么搞编程的看到别人的代码的时候第一反应就是重构，难道是别人写的真的差么，个人的有一下几个短见：

- 写的真的有些差劲，没有什么原则，规范，实践可谈
- 我们要从为什么当时他会这么写来考虑，会不会当时那种实现方式是比较好的呢
- 我们重构的目的是什么：是从一个不熟悉的代码变为自己熟悉的代码？还是要遵循什么最佳实践

**Comment by miaozilong** [comment]
程序员最累的就是没有不重构的代码
就像修路的,经常要拆了重修
